---
name: "Uptime Kuma (Docker Socket)"
version: latest
slug: uptime
description: Uptime monitoring tool based on Uptime Kuma
url: https://github.com/hassio-addons/app-uptime-kuma
webui: http://[HOST]:[PORT:3001]
init: false
image: "ghcr.io/rpetrina/uptime-kuma-docsock"
arch:
  - aarch64
ports:
  3001/tcp: 3001
watchdog: "http://[HOST]:[PORT:3001]"
host_network: true
startup: application
boot: auto
environment:
  UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN: "true"
  DOCKER_TLS_DIR_PATH: "/data/docker-tls"
  NODE_EXTRA_CA_CERTS: "/data/docker-tls/fullchain.pem"
options:
  SERVER_HOSTNAME: ""
schema:
  SERVER_HOSTNAME: str
map:
  - ssl:ro
hassio_api: true
hassio_role: admin
docker_api: true
ports_description:
  3001/tcp: Web interface
discovery:
  - uptime_kuma
